# Generated by Django 5.1.5 on 2025-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
