# Generated by Django 5.1.5 on 2025-02-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email2',
        ),
    ]
