# Generated by Django 5.1.6 on 2025-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostProductAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_location', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='lost_products/')),
                ('date_lost', models.DateField()),
                ('time_lost', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
