# Generated by Django 5.1.5 on 2025-02-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostproductad',
            name='user',
        ),
    ]
