# Generated by Django 5.1.6 on 2025-02-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_lostproductad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostproductad',
            old_name='date_lost',
            new_name='date_found',
        ),
        migrations.RenameField(
            model_name='lostproductad',
            old_name='time_lost',
            new_name='time_found',
        ),
    ]
