# Generated by Django 5.1.5 on 2025-02-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_lostproductadself_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostproductad',
            name='claim',
            field=models.BooleanField(default=False),
        ),
    ]
