# Generated by Django 5.1.5 on 2025-02-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostproductad',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_products/'),
        ),
    ]
